book-details:
    class-name: Extreme Python
    revision: 1.0  # current course revision
    extra: true # T if non-core modules needed
    licensed: true # T if need to put license info in footer
    non-python: true # T if non-python utilities needed

    author-name: John Strickler
    author-email: jstrickler@gmail.com
    toc: true
    doc-type: book
    source-highlighter: pygments
    include-file: allcourses_common.asc

    prefaces:
        - py3usgs_atc.asc

    chapter-days:
        - 
            day-label: Day 1
            chapters: 
                - virtual_environments.asc
                - pythonic_programming.asc
                - developer_tools.asc
                - logging.asc

        - 
            day-label: Day 2
            chapters:
                - unit_testing_pytest.asc
                - design_patterns.asc
                - packaging.asc
                - functional_tools.asc

        - 
            day-label: Day 3
            chapters:
                - container_classes.asc
                - generators_and_other_iterables.asc
                - metaprogramming.asc
                - advanced_xml.asc

        - 
            day-label: Day 4
            chapters:

                - multiprogramming.asc
                - network_programming.asc
                - consuming_rest_data.asc
                - ipython_and_jupyter.asc  # make sure notebooks and their data files are present

            day-label: Day 5
            chapters:
                - intro_to_numpy.asc
                - intro_to_scipy.asc
                - intro_to_pandas.asc
                - intro_to_matplotlib.asc

    appendices:
            - bibliography.asc
            - git_access.asc

    lab-files:  # student files for this course that are not specified by chapter files
        root:
            - pastable.py
            - script_template.py
            - where_do_i_go.py
        examples:
        data_text:
            - where_do_i_go.html
        data_binary:
        setup:
            - all_pycharm_settings.zip
            - gitignore
            - cookiecutter-python-module
        notebooks:

    non-python-flags: # flags for non-Python utilities
        pycharm: true # T if PyCharm should be in setup
        graphviz: true # T if GraphViz needed
        postman: true # T if PostMan needed
        kafka: false # T if kafka needed
        xcode: false # T if xcode needed
        docker: false # T if docker needed
        mingw: false # T if mingw needed
        git: true # T if git needed
        chromedriver  : false # T if chromedriver   needed
        ccompnote: false # T if C Compiler note needed

    vars:
