book-details:
    class-name: Extreme Python
    class-slug: pyextreme
    revision: 1.2  # current course revision
    licensed: true # T if need to put license info in footer
    
    author-name: John Strickler
    author-email: jstrickler@gmail.com
    toc: true
    doc-type: book
    source-highlighter: pygments
    include-file: allcourses_common.asc
    slides-theme: beige
    include-atc: true

    chapter-days:
        - 
            day-label: Day 1
            chapters: 
                - vs_code_setup.asc
                - virtual_environments.asc
                - pythonic_programming.asc
                - developer_tools.asc

        - 
            day-label: Day 2
            chapters:
                - logging.asc
                - type-hinting.asc
                - unit_testing_pytest.asc
                - packaging.asc

        - 
            day-label: Day 3
            chapters:
                - functional_tools.asc
                - container_classes.asc
                - iterables_and_generators.asc
                - metaprogramming.asc

        - 
            day-label: Day 4
            chapters:
                - advanced_xml.asc
                - multiprogramming.asc
                - consuming_rest_data.asc
                - ipython_and_jupyterlab.asc

    appendices:
            - bibliography.asc
            - network_programming.asc
            - git_access.asc
            - design_patterns.asc

    lab-files:  # student files for this course that are not specified by chapter files
        root:
            - pastable.py
            - script_template.py
            - where_do_i_go.py
        examples:
        data_text:
            - where_do_i_go.html
        data_binary:
        setup:
            - 
            - all_pycharm_settings.zip
            - gitignore
            - cookiecutter-python-module
        notebooks:

    ides:
        - vscode
